### ISSUE TITLE
Process was killed with SIGTERM

### ISSUE THREAD

**Issue by cryptowhizzard** [tech-greedy/singularity#140] opened 2022-08-30 15:42 UTC
2022-08-30T14:02:17.019Z [deal_tracking_service] info: Start update deal tracking - {}
2022-08-30T14:12:17.023Z [deal_tracking_service] info: Start update deal tracking - {}
2022-08-30T14:22:17.027Z [deal_tracking_service] info: Start update deal tracking - {}
2022-08-30T14:25:51.294Z [deal_preparation_worker] error: 54909790-d662-4bbe-9ab6-a57072c50870 Encountered an error. Process was killed with SIGTERM - {"code":null,"signal":"SIGTERM","stdout":"","stderr":"","stack":"Error: Process was killed with SIGTERM\n    at ChildProcess.done (/root/singularity/node_modules/promisify-child-process/index.cjs:72:19)\n    at ChildProcess.emit (node:events:527:28)\n    at maybeClose (node:internal/child_process:1092:16)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)"}
2022-08-30T14:25:51.298Z [deal_preparation_worker] info: 54909790-d662-4bbe-9ab6-a57072c50870 - The generation did not finish. - {"id":"62fff3d2f1260e9a7d4fbc54","datasetName":"1000genomes-dragen","index":10300}
2022-08-30T14:25:51.425Z [deal_preparation_worker] info: 54909790-d662-4bbe-9ab6-a57072c50870 - Polled a new generation request. - {"id":"62fff3d5f1260e9a7d4fddad","datasetName":"1000genomes-dragen","index":10477}
2022-08-30T14:32:17.030Z [deal_tracking_service] info: Start update deal tracking - {}
2022-08-30T14:36:56.709Z [deal_preparation_worker] error: 0d774cd8-787c-4e11-93a7-c97ecee3d03d Encountered an error. Process was killed with SIGTERM - {"code":null,"signal":"SIGTERM","stdout":"","stderr":"","stack":"Error: Process was killed with SIGTERM\n    at ChildProcess.done (/root/singularity/node_modules/promisify-child-process/index.cjs:72:19)\n    at ChildProcess.emit (node:events:527:28)\n    at maybeClose (node:internal/child_process:1092:16)\n    at Socket.<anonymous> (node:internal/child_process:451:11)\n    at Socket.emit (node:events:527:28)\n    at Pipe.<anonymous> (node:net:709:12)"}
2022-08-30T14:36:56.720Z [deal_preparation_worker] info: 0d774cd8-787c-4e11-93a7-c97ecee3d03d - The generation did not finish. - {"id":"62fff3d0f1260e9a7d4fa94f","datasetName":"1000genomes-dragen","index":10149}
2022-08-30T14:36:56.892Z [deal_preparation_worker] info: 0d774cd8-787c-4e11-93a7-c97ecee3d03d - Polled a new generation request. - {"id":"62fff3d6f1260e9a7d4fe31e","datasetName":"1000genomes-dragen","index":10520}
2022-08-30T14:42:17.034Z [deal_tracking_service] info: Start update deal tracking - {}
2022-08-30T14:52:17.041Z [deal_tracking_service] info: Start update deal tracking - {}
2022-08-30T15:02:17.042Z [deal_tracking_service] info: Start update deal tracking - {}
2022-08-30T15:12:17.050Z [deal_tracking_service] info: Start update deal tracking - {}
2022-08-30T15:22:17.056Z [deal_tracking_service] info: Start update deal tracking - {}
2022-08-30T15:32:17.058Z [deal_tracking_service] info: Start update deal tracking - {}

**Comment by xinaxu** [comment] 2022-08-30 16:01
This is expected when you pause or delete the request.

**Comment by cryptowhizzard** [comment] 2022-08-30 16:04
I did not pause nor delete. I am trying to build ;-)

**Comment by xinaxu** [comment] 2022-08-30 16:57
The SIGTERM is a user-level event. It can either be initiated by you or when the program detects that the generation request is no longer active, i.e. it is paused, no longer exist, or is in an errored state. 
If you're building something, it usually shouldn't generate a SIGTERM event, but if it does, the process gets killed and a new one will be spawned up in a later time.

**Comment by xinaxu** [comment] 2022-08-30 17:00
So unless you gets it in an infinite loop, this should not be a concern.

**Comment by xinaxu** [comment] 2022-09-17 05:10
Fixed in master. This is caused by health status being cleared when multiple nodes are running daemon.

**Closed by xinaxu** 2022-09-17 05:10 UTC
Labels: bug
