### ISSUE TITLE
Some random crashes during dataset building

### ISSUE THREAD

**Issue by cryptowhizzard** [tech-greedy/singularity#87] opened 2022-07-05 23:06 UTC
**Describe the bug**
2022-07-05T22:55:05.681Z [deal_tracking_service] info: Start update deal tracking - {}
2022-07-05T23:02:02.738Z [deal_preparation_worker] error: bf9f9d31-8790-422c-9877-5b41f345ed69 - Encountered an error. - {"stderr":"2022/07/05 22:51:27 error traversing node at \"Links/0/Hash/Links/0/Hash/Links/0/Hash/Links/8/Hash/Links/2/Hash/Links/100/Hash\": could not load link \"bafkreib3qfw2xg6f2vsxhz3ioxeirbgdfaeoh5pzr5347vyjdgs5i6fbom\": open /car2/cartmp/29c60aed-f42a-4d15-be4f-8064b1cd2bd2/level2/1994/01/10/KIWA/KIWA19940110_162721.gz: remote I/O error\n"}
2022-07-05T23:02:02.743Z [deal_preparation_worker] info: bf9f9d31-8790-422c-9877-5b41f345ed69 - Polled a new generation request. - {"id":"62c465366031ee8552ae96c0","datasetName":"nexrad1","index":46}
2022-07-05T23:02:07.447Z [deal_preparation_worker] error: ecf5a5ce-ad1b-4f88-9005-998e52b2373f - Encountered an error. - {"stderr":"panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7d32d8]\n\ngoroutine 1 [running]:\ngithub.com/ipfs/go-blockservice.(*blockService).AddBlock(0xc0001f2780, {0xaa6238, 0xc0000360a8}, {0x0?, 0x0?})\n\t/home/runner/go/pkg/mod/github.com/ipfs/go-blockservice@v0.3.0/blockservice.go:132 +0x58\ngithub.com/ipfs/go-merkledag.(*dagService).Add(0xc000208040, {0xaa6238, 0xc0000360a8}, {0x0?, 0x0})\n\t/home/runner/go/pkg/mod/github.com/ipfs/go-merkledag@v0.6.0/merkledag.go:60 +0x7b\ngithub.com/tech-greedy/go-generate-car/util.GenerateCar({0xaa6238, 0xc0000360a8}, {0xc000b00000, 0x5a86, 0x6aae?}, {0x7ffeb215e2d9, 0x7}, {0x7ffeb215e2e4, 0x31}, {0xaa1140, ...})\n\t/home/runner/work/go-generate-car/go-generate-car/util/chunk.go:205 +0x1648\nmain.main.func1(0xc0000fd720?)\n\t/home/runner/work/go-generate-car/go-generate-car/generate-car.go:121 +0x885\ngithub.com/urfave/cli/v2.(*App).RunContext(0xc0000f51e0, {0xaa6238?, 0xc0000360a0}, {0xc000032070, 0x7, 0x7})\n\t/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:322 +0x953\ngithub.com/urfave/cli/v2.(*App).Run(...)\n\t/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.4.0/app.go:224\nmain.main()\n\t/home/runner/work/go-generate-car/go-generate-car/generate-car.go:170 +0x59d\n"}
2022-07-05T23:02:07.452Z [deal_preparation_worker] info: ecf5a5ce-ad1b-4f88-9005-998e52b2373f - Polled a new generation request. - {"id":"62c4654d6031ee8552af9d8e","datasetName":"nexrad1","index":49}

**Version**
0.1.2

**To Reproduce**
Nexrad dataset building on a mounted goofys drive. No cache
goofys#noaa-nexrad-level2   /nexrad/level2        fuse     _netdev,allow_other,--file-mode=0666,--dir-mode=0777  0       0

**Extra info**

Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

goofys version 0.24.0-08534b28a2195d30bb3c45dce0b834f3696028b8
No manual generate-car compiled .. this is the default from package.

**Comment by liuziba** [comment] 2022-07-06 05:08
This is caused by goofys, or the underlying network instabiliy. The remote I/O indicates there is some network issue when reading from S3 bucket. The segmentation fault, unfortunately is trying to read from a file handle that does not exist. Neither of them can be really fixed in `singularity`. 
What you can do is to do a retry. Other ways to make it less likely to happen is to use a tmpdir, or to download the dataset to the disk completely before starting the request.

**Comment by kernelogic** [comment] 2022-07-06 05:10
Can we auto retry for a few times when we detect a I/O error? This way user won't need to manually issue a retry

**Comment by liuziba** [comment] 2022-07-06 05:28
The software wouldn't know which error is retryable and which is not - in fact, if it's a physical drive, most I/O error is not retryable. Retry can also cause avalanche and make error more likely to occur.

**Comment by liuziba** [comment] 2022-07-07 23:33
v1.0.0 has fixed the segmentation fault. It should now properly shows what's going wrong with that request.
Meanwhile, adding troubleshooting guide for remote I/O error here
https://github.com/tech-greedy/singularity/blob/main/README.md#error---open-somefile-remote-io-error

**Closed** 2022-07-11 23:25 UTC
Labels: bug
